export const NavigationPaths = {

    BOTTOM_TAB_NAVIGATION: "BOTTOM_TAB_NAVIGATION",

    RECORDS_SCREEN: "RECORDS_SCREEN",
    MAIL_TEMPLATES_SCREEN: "MAIL_TEMPLATES_SCREEN",
    PROFILE_SCREEN: "PROFILE_SCREEN",

    ADD_EDIT_MAIL_TEMPLATES_SCREEN: "ADD_EDIT_MAIL_TEMPLATES_SCREEN",
}